title: "Riley Tavassoli"
description: "Consciousness, Music, and Artificial Intelligence"
baseurl: ""
url: "https://rtavasso.github.io"

# Social links
github_username: rtavasso
linkedin_username: rtavasso

# Site settings
show_excerpts: true
permalink: /:year/:month/:day/:title/
timezone: America/New_York

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
social:
  links:
    - https://github.com/rtavasso
    - https://www.linkedin.com/in/rtavasso/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/ 